import { Provider } from 'app/provider'
import { StylesProvider } from './styles-provider'
import '../app/globals.css'
import { Sidebar } from 'app/components/navigation/sidebar.web'

export const metadata = {
  title: 'Create Solito App',
  description: 'Generated by create Solito app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StylesProvider>
          <Provider>
            <div className="flex h-screen w-full text-white selection:bg-brand-gold selection:text-black overflow-hidden relative">
              <Sidebar />
              {/* Main Content Area */}
              <div className="flex-1 flex flex-col relative z-10 h-full overflow-y-auto">
                <main className="flex-1 w-full relative">
                  {children}
                </main>
              </div>
            </div>
          </Provider>
        </StylesProvider>
      </body>
    </html>
  )
}
